algorithm: supervised
al_algorithm: kmeans
save_dir: ./saved_models/al_algorithms/
save_name: kmeans_test_cifar10_400_0
resume: True
load_path: ./saved_models/al_algorithms/kmeans_test_cifar10_400_0/latest_model.pth
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 20
num_train_iter: 2000
num_log_iter: 100
num_eval_iter: 200
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 2000
num_labels: 400
label_epochs: [0,1,2,3,4,5]
num_query_epochs: [200,10,10,10,10,160]
uratio: 1
ema_m: 0.0
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 0.0005
layer_decay: 0.5
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch2_32
net_from_name: False
data_dir: ./data
dataset: cifar10
train_sampler: RandomSampler
num_classes: 10
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10026
dist_backend: nccl
gpu: None
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth
